### ISSUE TITLE
Require remarks for HL/SL leave?

### ISSUE THREAD

**Issue by dima-ser** [ctcdev/tlr#1]
When testing the new changes with our folks, a question came up if it should require a remark when submitting SL/HL entries in PartTime timesheet (just like it does for the FullTime right now)

**Comment by nicswan** [comment]
Hi @dima-ser - Sorry for the slow reply, I didn't get a notification of your question. I think if you want to require this, it would be your call and would require custom coding - though you would essentially "just" need to port the remark requirement/checking functionality from the full-time/salaried timesheet to the part-time/hourly timesheet logic.

At Bellevue College, we currently do not require remarks for regular sick time or vacation for full-time/salaried folks.  For ourselves, we'd probably only make this change if we hear definitely from supervisors that it's needed.

**Comment by dima-ser** [comment]
Thanks Nicole
