### ISSUE TITLE
Fix for new Part Time liEntryType - verbiage changes (from Jim)

### ISSUE THREAD

**Issue by everettcc** [ctcdev/tlr#2]
Working with Jim Craswell, we came up with the following subtle changes to the controls/TSPartTime.ascx file addressing the checkbox/label arrangement and verbiage :

    <li id="liEntryType" runat="server">
        <label for="<%=chkbxEnterType.ClientID%>">Sick Leave :</label>
        <span>
        <asp:Checkbox id="chkbxEnterType" value="true" runat="server" />
        <%
            If chkbxEnterType.Checked Then
                ddlEntryType.CssClass = "field"
            Else
                ddlEntryType.CssClass = "field hide"
            End If
        %>

        <asp:DropDownList ID="ddlEntryType" runat="server" DataTextField="LeaveType" DataValueField="EntryTypeID" />

        </span>

    </li>

**Comment by nicswan** [comment]
You can definitely alter the code/verbiage in the app however you would like.  The logic behind leaving it more general was to future proof the app to an extent.  Entry (leave) types available to employees are controlled in the database by mapping entry types to employee types. It's certainly possible that hourly employees might have additional leave types in the future - ones that aren't specifically sick leave - and in this scenario, then only the database end would need updated (i.e. map the new entry type to the employee type and possibly update leave balance checking logic in the appropriate stored procedure).
